[tool.poetry]
name = "pattern-finder-gui"
version = "0.1.0"
description = ""
authors = ["Lab Rat <dev.frolics@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ttkthemes = "^3.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
